<?php
/**
 * @file
 * Code for the Serchilo feature.
 */

include_once 'serchilo.features.inc';

function serchilo_revisionapi($op, $node) {

  if ($op == 'post publish') {
    if ($node->type == 'shortcut') {
      $command_id = drupal_array_get_nested_value($node->field_command_id, array(LANGUAGE_NONE, 0, 'value'));
      if (empty($command_id)) {
        $command_id = serchilo_insert_shortcut_row($node);
        drupal_array_set_nested_value($node->field_command_id, array(LANGUAGE_NONE, 0, 'value'), $command_id);
        node_save($node);
      }
      else {
        serchilo_update_shortcut_row($node);
      }
    }
  }
}

/**
 * Implements hook_node_presave().
 */
function serchilo_node_presave($node) {

  if ($node->type == 'shortcut') {
    $no_moderation = (
      (property_exists($node, 'revision_operation')) && 
      ($node->revision_operation == REVISIONING_NEW_REVISION_NO_MODERATION)
    );
    if ($no_moderation) {
      $command_id = drupal_array_get_nested_value($node->field_command_id, array(LANGUAGE_NONE, 0, 'value'));
      if (empty($command_id)) {
        $command_id = serchilo_insert_shortcut_row($node);
        drupal_array_set_nested_value($node->field_command_id, array(LANGUAGE_NONE, 0, 'value'), $command_id);
        dpm('inserted');
      }
      else {
        serchilo_update_shortcut_row($node);
        dpm('updated');
      }
    }
  }
}

/**
 * Implements hook_node_delete().
 */
function serchilo_node_delete($node) {
  if ($node->type == 'shortcut') {
    $command_id = drupal_array_get_nested_value($node->field_command_id, array(LANGUAGE_NONE, 0, 'value'));
    if (!empty($command_id)) {
      serchilo_delete_shortcut_row($node);
    }
  }
}

/**
 * Retrieve database fields from shortcut node.
 *
 * @param $node
 *   Node of type shortcut
 * @return
 *   array to pass to fields()
 */
function serchilo_shortcut_to_db_fields($node) {

  drupal_array_set_nested_value($node->field_argument_names, array(LANGUAGE_NONE, 0, 'value'), '');
  $fields = array(
    'title' => $node->title,
    'keyword' => $node->field_keyword[LANGUAGE_NONE][0]['value'],
    'argument_names' => $node->field_argument_names[LANGUAGE_NONE][0]['value'],
    'argument_count' => $node->field_argument_count[LANGUAGE_NONE][0]['value'],
    'url' => $node->field_url[LANGUAGE_NONE][0]['value'],
    'weight' => $node->field_weight[LANGUAGE_NONE][0]['value'],
    'invisible' => $node->field_invisible[LANGUAGE_NONE][0]['value'],
    'set_referrer' => $node->field_set_referrer[LANGUAGE_NONE][0]['value'],
  );

  return $fields;
}

function serchilo_insert_shortcut_row($node) {
  $fields = serchilo_shortcut_to_db_fields($node);
  $command_id = db_insert('serchilo_shortcut') 
    ->fields($fields)
    ->execute();
  // TODO
  // raise error when $command_id < 1
  dpm($command_id);
  return $command_id;
}

function serchilo_update_shortcut_row($node) {
  $fields = serchilo_shortcut_to_db_fields($node);
  $num_updated = db_update('serchilo_shortcut') 
    ->fields($fields)
    ->condition('id', $node->field_command_id[LANGUAGE_NONE][0]['value'] )
    ->execute();
  // TODO
  // raise error when $num_updated != 1
  dpm($num_updated);
}

function serchilo_delete_shortcut_row($node) {
  $num_deleted = db_delete('serchilo_shortcut') 
    ->condition('id', $node->field_command_id[LANGUAGE_NONE][0]['value'] )
    ->execute();
  // TODO
  // raise error when $num_deleted != 1
  dpm($num_deleted);
}
