<?PHP

define('SERCHILO_DEFAULT_LANGUAGE', 'en');
define('SERCHILO_DEFAULT_COUNTRY', 'deu');
//define('SERCHILO_DEFAULT_COUNTRY', 'usa');
define('SERCHILO_NAMESPACE_PATH_SEPARATOR', '.');
define('SERCHILO_PLANET_NAMESPACE', 'o');

define('SERCHILO_NAMESPACES_PATH_AFFIX', 'n');
define('SERCHILO_USER_PATH_AFFIX', 'u');

define('SERCHILO_CONSOLE', 'console');
define('SERCHILO_AUTOCOMPLETE_PATH_AFFIX', 'ajax');
define('SERCHILO_OPENSEARCH_DEFINITION_PATH_AFFIX', 'opensearch');
define('SERCHILO_OPENSEARCH_SUGGESTIONS_PATH_AFFIX', 'opensearch-suggestions');
define('SERCHILO_URL_PATH_AFFIX', 'url');
define('SERCHILO_API_PATH_AFFIX', 'api');

// TODO: Delete obsolete:
define('SERCHILO_METATAG_INSTANCE_CONSOLE', 'serchilo_console');
define('SERCHILO_METATAG_INSTANCE_CONSOLE_NAMESPACES', 'serchilo_console:namespaces');
define('SERCHILO_METATAG_INSTANCE_CONSOLE_USER', 'serchilo_console:user');
