<?PHP

define('DEFAULT_LANGUAGE', 'en');
define('DEFAULT_COUNTRY', 'deu');
#define('DEFAULT_COUNTRY', 'usa');
define('DEFAULT_LIMIT', 8);
define('NAMESPACE_PATH_SEPARATOR', '.');
define('STAR_NAMESPACE', 'o');

define('NAMESPACES_PATH_AFFIX', 'n');
define('USER_PATH_AFFIX', 'u');

define('CONSOLE', 'console');
define('AUTOCOMPLETE_PATH_AFFIX', 'ajax');
define('OPENSEARCH_DEFINITION_PATH_AFFIX', 'opensearch');
define('OPENSEARCH_SUGGESTIONS_PATH_AFFIX', 'opensearch-suggestions');
define('URL_PATH_AFFIX', 'url');
define('API_PATH_AFFIX', 'api');

define('METATAG_INSTANCE_CONSOLE', 'serchilo_console');
define('METATAG_INSTANCE_CONSOLE_NAMESPACES', 'serchilo_console:namespaces');
define('METATAG_INSTANCE_CONSOLE_USER', 'serchilo_console:user');

