<?php
/**
 * @file
 * serchilo_features.features.language.inc
 */

/**
 * Implements hook_locale_default_languages().
 */
function serchilo_features_locale_default_languages() {
  $languages = array();

  // Exported language: aa.
  $languages['aa'] = array(
    'language' => 'aa',
    'name' => 'Afar',
    'native' => 'Afar',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'aa',
    'weight' => 0,
  );
  // Exported language: ab.
  $languages['ab'] = array(
    'language' => 'ab',
    'name' => 'Abkhazian',
    'native' => 'аҧсуа бызшәа',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ab',
    'weight' => 0,
  );
  // Exported language: ae.
  $languages['ae'] = array(
    'language' => 'ae',
    'name' => 'Avestan',
    'native' => 'Avestan',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ae',
    'weight' => 0,
  );
  // Exported language: af.
  $languages['af'] = array(
    'language' => 'af',
    'name' => 'Afrikaans',
    'native' => 'Afrikaans',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'af',
    'weight' => 0,
  );
  // Exported language: ak.
  $languages['ak'] = array(
    'language' => 'ak',
    'name' => 'Akan',
    'native' => 'Akan',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ak',
    'weight' => 0,
  );
  // Exported language: am.
  $languages['am'] = array(
    'language' => 'am',
    'name' => 'Amharic',
    'native' => 'አማርኛ',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'am',
    'weight' => 0,
  );
  // Exported language: ar.
  $languages['ar'] = array(
    'language' => 'ar',
    'name' => 'Arabic',
    'native' => 'العربية',
    'direction' => 1,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ar',
    'weight' => 0,
  );
  // Exported language: as.
  $languages['as'] = array(
    'language' => 'as',
    'name' => 'Assamese',
    'native' => 'Assamese',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'as',
    'weight' => 0,
  );
  // Exported language: av.
  $languages['av'] = array(
    'language' => 'av',
    'name' => 'Avar',
    'native' => 'Avar',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'av',
    'weight' => 0,
  );
  // Exported language: ay.
  $languages['ay'] = array(
    'language' => 'ay',
    'name' => 'Aymara',
    'native' => 'Aymara',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ay',
    'weight' => 0,
  );
  // Exported language: az.
  $languages['az'] = array(
    'language' => 'az',
    'name' => 'Azerbaijani',
    'native' => 'azərbaycan',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'az',
    'weight' => 0,
  );
  // Exported language: ba.
  $languages['ba'] = array(
    'language' => 'ba',
    'name' => 'Bashkir',
    'native' => 'Bashkir',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ba',
    'weight' => 0,
  );
  // Exported language: be.
  $languages['be'] = array(
    'language' => 'be',
    'name' => 'Belarusian',
    'native' => 'Беларуская',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'be',
    'weight' => 0,
  );
  // Exported language: bg.
  $languages['bg'] = array(
    'language' => 'bg',
    'name' => 'Bulgarian',
    'native' => 'Български',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'bg',
    'weight' => 0,
  );
  // Exported language: bh.
  $languages['bh'] = array(
    'language' => 'bh',
    'name' => 'Bihari',
    'native' => 'Bihari',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'bh',
    'weight' => 0,
  );
  // Exported language: bi.
  $languages['bi'] = array(
    'language' => 'bi',
    'name' => 'Bislama',
    'native' => 'Bislama',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'bi',
    'weight' => 0,
  );
  // Exported language: bm.
  $languages['bm'] = array(
    'language' => 'bm',
    'name' => 'Bambara',
    'native' => 'Bamanankan',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'bm',
    'weight' => 0,
  );
  // Exported language: bn.
  $languages['bn'] = array(
    'language' => 'bn',
    'name' => 'Bengali',
    'native' => 'Bengali',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'bn',
    'weight' => 0,
  );
  // Exported language: bo.
  $languages['bo'] = array(
    'language' => 'bo',
    'name' => 'Tibetan',
    'native' => 'Tibetan',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'bo',
    'weight' => 0,
  );
  // Exported language: br.
  $languages['br'] = array(
    'language' => 'br',
    'name' => 'Breton',
    'native' => 'Breton',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'br',
    'weight' => 0,
  );
  // Exported language: bs.
  $languages['bs'] = array(
    'language' => 'bs',
    'name' => 'Bosnian',
    'native' => 'Bosanski',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'bs',
    'weight' => 0,
  );
  // Exported language: ca.
  $languages['ca'] = array(
    'language' => 'ca',
    'name' => 'Catalan',
    'native' => 'Català',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ca',
    'weight' => 0,
  );
  // Exported language: ce.
  $languages['ce'] = array(
    'language' => 'ce',
    'name' => 'Chechen',
    'native' => 'Chechen',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ce',
    'weight' => 0,
  );
  // Exported language: ch.
  $languages['ch'] = array(
    'language' => 'ch',
    'name' => 'Chamorro',
    'native' => 'Chamorro',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ch',
    'weight' => 0,
  );
  // Exported language: co.
  $languages['co'] = array(
    'language' => 'co',
    'name' => 'Corsican',
    'native' => 'Corsican',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'co',
    'weight' => 0,
  );
  // Exported language: cr.
  $languages['cr'] = array(
    'language' => 'cr',
    'name' => 'Cree',
    'native' => 'Cree',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'cr',
    'weight' => 0,
  );
  // Exported language: cs.
  $languages['cs'] = array(
    'language' => 'cs',
    'name' => 'Czech',
    'native' => 'Čeština',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'cs',
    'weight' => 0,
  );
  // Exported language: cu.
  $languages['cu'] = array(
    'language' => 'cu',
    'name' => 'Old Slavonic',
    'native' => 'Old Slavonic',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'cu',
    'weight' => 0,
  );
  // Exported language: cv.
  $languages['cv'] = array(
    'language' => 'cv',
    'name' => 'Chuvash',
    'native' => 'Chuvash',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'cv',
    'weight' => 0,
  );
  // Exported language: cy.
  $languages['cy'] = array(
    'language' => 'cy',
    'name' => 'Welsh',
    'native' => 'Cymraeg',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'cy',
    'weight' => 0,
  );
  // Exported language: da.
  $languages['da'] = array(
    'language' => 'da',
    'name' => 'Danish',
    'native' => 'Dansk',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'da',
    'weight' => 0,
  );
  // Exported language: de.
  $languages['de'] = array(
    'language' => 'de',
    'name' => 'German',
    'native' => 'Deutsch',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'de',
    'weight' => 0,
  );
  // Exported language: dv.
  $languages['dv'] = array(
    'language' => 'dv',
    'name' => 'Maldivian',
    'native' => 'Maldivian',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'dv',
    'weight' => 0,
  );
  // Exported language: dz.
  $languages['dz'] = array(
    'language' => 'dz',
    'name' => 'Bhutani',
    'native' => 'Bhutani',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'dz',
    'weight' => 0,
  );
  // Exported language: ee.
  $languages['ee'] = array(
    'language' => 'ee',
    'name' => 'Ewe',
    'native' => 'Ɛʋɛ',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ee',
    'weight' => 0,
  );
  // Exported language: el.
  $languages['el'] = array(
    'language' => 'el',
    'name' => 'Greek',
    'native' => 'Ελληνικά',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'el',
    'weight' => 0,
  );
  // Exported language: en.
  $languages['en'] = array(
    'language' => 'en',
    'name' => 'English',
    'native' => 'English',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => '',
    'weight' => 0,
  );
  // Exported language: eo.
  $languages['eo'] = array(
    'language' => 'eo',
    'name' => 'Esperanto',
    'native' => 'Esperanto',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'eo',
    'weight' => 0,
  );
  // Exported language: es.
  $languages['es'] = array(
    'language' => 'es',
    'name' => 'Spanish',
    'native' => 'Español',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'es',
    'weight' => 0,
  );
  // Exported language: et.
  $languages['et'] = array(
    'language' => 'et',
    'name' => 'Estonian',
    'native' => 'Eesti',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'et',
    'weight' => 0,
  );
  // Exported language: eu.
  $languages['eu'] = array(
    'language' => 'eu',
    'name' => 'Basque',
    'native' => 'Euskera',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'eu',
    'weight' => 0,
  );
  // Exported language: fa.
  $languages['fa'] = array(
    'language' => 'fa',
    'name' => 'Persian',
    'native' => 'فارسی',
    'direction' => 1,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'fa',
    'weight' => 0,
  );
  // Exported language: ff.
  $languages['ff'] = array(
    'language' => 'ff',
    'name' => 'Fulah',
    'native' => 'Fulfulde',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ff',
    'weight' => 0,
  );
  // Exported language: fi.
  $languages['fi'] = array(
    'language' => 'fi',
    'name' => 'Finnish',
    'native' => 'Suomi',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'fi',
    'weight' => 0,
  );
  // Exported language: fj.
  $languages['fj'] = array(
    'language' => 'fj',
    'name' => 'Fiji',
    'native' => 'Fiji',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'fj',
    'weight' => 0,
  );
  // Exported language: fo.
  $languages['fo'] = array(
    'language' => 'fo',
    'name' => 'Faeroese',
    'native' => 'Faeroese',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'fo',
    'weight' => 0,
  );
  // Exported language: fr.
  $languages['fr'] = array(
    'language' => 'fr',
    'name' => 'French',
    'native' => 'Français',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'fr',
    'weight' => 0,
  );
  // Exported language: fy.
  $languages['fy'] = array(
    'language' => 'fy',
    'name' => 'Frisian',
    'native' => 'Frysk',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'fy',
    'weight' => 0,
  );
  // Exported language: ga.
  $languages['ga'] = array(
    'language' => 'ga',
    'name' => 'Irish',
    'native' => 'Gaeilge',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ga',
    'weight' => 0,
  );
  // Exported language: gd.
  $languages['gd'] = array(
    'language' => 'gd',
    'name' => 'Scots Gaelic',
    'native' => 'Scots Gaelic',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'gd',
    'weight' => 0,
  );
  // Exported language: gl.
  $languages['gl'] = array(
    'language' => 'gl',
    'name' => 'Galician',
    'native' => 'Galego',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'gl',
    'weight' => 0,
  );
  // Exported language: gn.
  $languages['gn'] = array(
    'language' => 'gn',
    'name' => 'Guarani',
    'native' => 'Guarani',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'gn',
    'weight' => 0,
  );
  // Exported language: gu.
  $languages['gu'] = array(
    'language' => 'gu',
    'name' => 'Gujarati',
    'native' => 'Gujarati',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'gu',
    'weight' => 0,
  );
  // Exported language: gv.
  $languages['gv'] = array(
    'language' => 'gv',
    'name' => 'Manx',
    'native' => 'Manx',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'gv',
    'weight' => 0,
  );
  // Exported language: ha.
  $languages['ha'] = array(
    'language' => 'ha',
    'name' => 'Hausa',
    'native' => 'Hausa',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ha',
    'weight' => 0,
  );
  // Exported language: he.
  $languages['he'] = array(
    'language' => 'he',
    'name' => 'Hebrew',
    'native' => 'עברית',
    'direction' => 1,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'he',
    'weight' => 0,
  );
  // Exported language: hi.
  $languages['hi'] = array(
    'language' => 'hi',
    'name' => 'Hindi',
    'native' => 'हिन्दी',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'hi',
    'weight' => 0,
  );
  // Exported language: ho.
  $languages['ho'] = array(
    'language' => 'ho',
    'name' => 'Hiri Motu',
    'native' => 'Hiri Motu',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ho',
    'weight' => 0,
  );
  // Exported language: hr.
  $languages['hr'] = array(
    'language' => 'hr',
    'name' => 'Croatian',
    'native' => 'Hrvatski',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'hr',
    'weight' => 0,
  );
  // Exported language: ht.
  $languages['ht'] = array(
    'language' => 'ht',
    'name' => 'Haitian Creole',
    'native' => 'Haitian Creole',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ht',
    'weight' => 0,
  );
  // Exported language: hu.
  $languages['hu'] = array(
    'language' => 'hu',
    'name' => 'Hungarian',
    'native' => 'Magyar',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'hu',
    'weight' => 0,
  );
  // Exported language: hy.
  $languages['hy'] = array(
    'language' => 'hy',
    'name' => 'Armenian',
    'native' => 'Հայերեն',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'hy',
    'weight' => 0,
  );
  // Exported language: hz.
  $languages['hz'] = array(
    'language' => 'hz',
    'name' => 'Herero',
    'native' => 'Herero',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'hz',
    'weight' => 0,
  );
  // Exported language: ia.
  $languages['ia'] = array(
    'language' => 'ia',
    'name' => 'Interlingua',
    'native' => 'Interlingua',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ia',
    'weight' => 0,
  );
  // Exported language: id.
  $languages['id'] = array(
    'language' => 'id',
    'name' => 'Indonesian',
    'native' => 'Bahasa Indonesia',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'id',
    'weight' => 0,
  );
  // Exported language: ie.
  $languages['ie'] = array(
    'language' => 'ie',
    'name' => 'Interlingue',
    'native' => 'Interlingue',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ie',
    'weight' => 0,
  );
  // Exported language: ig.
  $languages['ig'] = array(
    'language' => 'ig',
    'name' => 'Igbo',
    'native' => 'Igbo',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ig',
    'weight' => 0,
  );
  // Exported language: ik.
  $languages['ik'] = array(
    'language' => 'ik',
    'name' => 'Inupiak',
    'native' => 'Inupiak',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ik',
    'weight' => 0,
  );
  // Exported language: is.
  $languages['is'] = array(
    'language' => 'is',
    'name' => 'Icelandic',
    'native' => 'Íslenska',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'is',
    'weight' => 0,
  );
  // Exported language: it.
  $languages['it'] = array(
    'language' => 'it',
    'name' => 'Italian',
    'native' => 'Italiano',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'it',
    'weight' => 0,
  );
  // Exported language: iu.
  $languages['iu'] = array(
    'language' => 'iu',
    'name' => 'Inuktitut',
    'native' => 'Inuktitut',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'iu',
    'weight' => 0,
  );
  // Exported language: ja.
  $languages['ja'] = array(
    'language' => 'ja',
    'name' => 'Japanese',
    'native' => '日本語',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ja',
    'weight' => 0,
  );
  // Exported language: jv.
  $languages['jv'] = array(
    'language' => 'jv',
    'name' => 'Javanese',
    'native' => 'Javanese',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'jv',
    'weight' => 0,
  );
  // Exported language: ka.
  $languages['ka'] = array(
    'language' => 'ka',
    'name' => 'Georgian',
    'native' => 'Georgian',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ka',
    'weight' => 0,
  );
  // Exported language: kg.
  $languages['kg'] = array(
    'language' => 'kg',
    'name' => 'Kongo',
    'native' => 'Kongo',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'kg',
    'weight' => 0,
  );
  // Exported language: ki.
  $languages['ki'] = array(
    'language' => 'ki',
    'name' => 'Kikuyu',
    'native' => 'Kikuyu',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ki',
    'weight' => 0,
  );
  // Exported language: kj.
  $languages['kj'] = array(
    'language' => 'kj',
    'name' => 'Kwanyama',
    'native' => 'Kwanyama',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'kj',
    'weight' => 0,
  );
  // Exported language: kk.
  $languages['kk'] = array(
    'language' => 'kk',
    'name' => 'Kazakh',
    'native' => 'Қазақ',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'kk',
    'weight' => 0,
  );
  // Exported language: kl.
  $languages['kl'] = array(
    'language' => 'kl',
    'name' => 'Greenlandic',
    'native' => 'Greenlandic',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'kl',
    'weight' => 0,
  );
  // Exported language: km.
  $languages['km'] = array(
    'language' => 'km',
    'name' => 'Cambodian',
    'native' => 'Cambodian',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'km',
    'weight' => 0,
  );
  // Exported language: kn.
  $languages['kn'] = array(
    'language' => 'kn',
    'name' => 'Kannada',
    'native' => 'ಕನ್ನಡ',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'kn',
    'weight' => 0,
  );
  // Exported language: ko.
  $languages['ko'] = array(
    'language' => 'ko',
    'name' => 'Korean',
    'native' => '한국어',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ko',
    'weight' => 0,
  );
  // Exported language: kr.
  $languages['kr'] = array(
    'language' => 'kr',
    'name' => 'Kanuri',
    'native' => 'Kanuri',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'kr',
    'weight' => 0,
  );
  // Exported language: ks.
  $languages['ks'] = array(
    'language' => 'ks',
    'name' => 'Kashmiri',
    'native' => 'Kashmiri',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ks',
    'weight' => 0,
  );
  // Exported language: ku.
  $languages['ku'] = array(
    'language' => 'ku',
    'name' => 'Kurdish',
    'native' => 'Kurdî',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ku',
    'weight' => 0,
  );
  // Exported language: kv.
  $languages['kv'] = array(
    'language' => 'kv',
    'name' => 'Komi',
    'native' => 'Komi',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'kv',
    'weight' => 0,
  );
  // Exported language: kw.
  $languages['kw'] = array(
    'language' => 'kw',
    'name' => 'Cornish',
    'native' => 'Cornish',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'kw',
    'weight' => 0,
  );
  // Exported language: ky.
  $languages['ky'] = array(
    'language' => 'ky',
    'name' => 'Kyrgyz',
    'native' => 'Кыргызча',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ky',
    'weight' => 0,
  );
  // Exported language: la.
  $languages['la'] = array(
    'language' => 'la',
    'name' => 'Latin',
    'native' => 'Latina',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'la',
    'weight' => 0,
  );
  // Exported language: lb.
  $languages['lb'] = array(
    'language' => 'lb',
    'name' => 'Luxembourgish',
    'native' => 'Luxembourgish',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'lb',
    'weight' => 0,
  );
  // Exported language: lg.
  $languages['lg'] = array(
    'language' => 'lg',
    'name' => 'Luganda',
    'native' => 'Luganda',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'lg',
    'weight' => 0,
  );
  // Exported language: ln.
  $languages['ln'] = array(
    'language' => 'ln',
    'name' => 'Lingala',
    'native' => 'Lingala',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ln',
    'weight' => 0,
  );
  // Exported language: lo.
  $languages['lo'] = array(
    'language' => 'lo',
    'name' => 'Laothian',
    'native' => 'Laothian',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'lo',
    'weight' => 0,
  );
  // Exported language: lt.
  $languages['lt'] = array(
    'language' => 'lt',
    'name' => 'Lithuanian',
    'native' => 'Lietuvių',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'lt',
    'weight' => 0,
  );
  // Exported language: lv.
  $languages['lv'] = array(
    'language' => 'lv',
    'name' => 'Latvian',
    'native' => 'Latviešu',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'lv',
    'weight' => 0,
  );
  // Exported language: mg.
  $languages['mg'] = array(
    'language' => 'mg',
    'name' => 'Malagasy',
    'native' => 'Malagasy',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'mg',
    'weight' => 0,
  );
  // Exported language: mh.
  $languages['mh'] = array(
    'language' => 'mh',
    'name' => 'Marshallese',
    'native' => 'Marshallese',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'mh',
    'weight' => 0,
  );
  // Exported language: mi.
  $languages['mi'] = array(
    'language' => 'mi',
    'name' => 'Māori',
    'native' => 'Māori',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'mi',
    'weight' => 0,
  );
  // Exported language: mk.
  $languages['mk'] = array(
    'language' => 'mk',
    'name' => 'Macedonian',
    'native' => 'Македонски',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'mk',
    'weight' => 0,
  );
  // Exported language: ml.
  $languages['ml'] = array(
    'language' => 'ml',
    'name' => 'Malayalam',
    'native' => 'മലയാളം',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ml',
    'weight' => 0,
  );
  // Exported language: mn.
  $languages['mn'] = array(
    'language' => 'mn',
    'name' => 'Mongolian',
    'native' => 'Mongolian',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'mn',
    'weight' => 0,
  );
  // Exported language: mo.
  $languages['mo'] = array(
    'language' => 'mo',
    'name' => 'Moldavian',
    'native' => 'Moldavian',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'mo',
    'weight' => 0,
  );
  // Exported language: mr.
  $languages['mr'] = array(
    'language' => 'mr',
    'name' => 'Marathi',
    'native' => 'Marathi',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'mr',
    'weight' => 0,
  );
  // Exported language: ms.
  $languages['ms'] = array(
    'language' => 'ms',
    'name' => 'Malay',
    'native' => 'Bahasa Melayu',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ms',
    'weight' => 0,
  );
  // Exported language: mt.
  $languages['mt'] = array(
    'language' => 'mt',
    'name' => 'Maltese',
    'native' => 'Malti',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'mt',
    'weight' => 0,
  );
  // Exported language: my.
  $languages['my'] = array(
    'language' => 'my',
    'name' => 'Burmese',
    'native' => 'Burmese',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'my',
    'weight' => 0,
  );
  // Exported language: na.
  $languages['na'] = array(
    'language' => 'na',
    'name' => 'Nauru',
    'native' => 'Nauru',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'na',
    'weight' => 0,
  );
  // Exported language: nb.
  $languages['nb'] = array(
    'language' => 'nb',
    'name' => 'Norwegian Bokmål',
    'native' => 'Bokmål',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'nb',
    'weight' => 0,
  );
  // Exported language: nd.
  $languages['nd'] = array(
    'language' => 'nd',
    'name' => 'North Ndebele',
    'native' => 'North Ndebele',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'nd',
    'weight' => 0,
  );
  // Exported language: ne.
  $languages['ne'] = array(
    'language' => 'ne',
    'name' => 'Nepali',
    'native' => 'Nepali',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ne',
    'weight' => 0,
  );
  // Exported language: ng.
  $languages['ng'] = array(
    'language' => 'ng',
    'name' => 'Ndonga',
    'native' => 'Ndonga',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ng',
    'weight' => 0,
  );
  // Exported language: nl.
  $languages['nl'] = array(
    'language' => 'nl',
    'name' => 'Dutch',
    'native' => 'Nederlands',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'nl',
    'weight' => 0,
  );
  // Exported language: nn.
  $languages['nn'] = array(
    'language' => 'nn',
    'name' => 'Norwegian Nynorsk',
    'native' => 'Nynorsk',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'nn',
    'weight' => 0,
  );
  // Exported language: nr.
  $languages['nr'] = array(
    'language' => 'nr',
    'name' => 'South Ndebele',
    'native' => 'South Ndebele',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'nr',
    'weight' => 0,
  );
  // Exported language: nv.
  $languages['nv'] = array(
    'language' => 'nv',
    'name' => 'Navajo',
    'native' => 'Navajo',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'nv',
    'weight' => 0,
  );
  // Exported language: ny.
  $languages['ny'] = array(
    'language' => 'ny',
    'name' => 'Chichewa',
    'native' => 'Chichewa',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ny',
    'weight' => 0,
  );
  // Exported language: oc.
  $languages['oc'] = array(
    'language' => 'oc',
    'name' => 'Occitan',
    'native' => 'Occitan',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'oc',
    'weight' => 0,
  );
  // Exported language: om.
  $languages['om'] = array(
    'language' => 'om',
    'name' => 'Oromo',
    'native' => 'Oromo',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'om',
    'weight' => 0,
  );
  // Exported language: or.
  $languages['or'] = array(
    'language' => 'or',
    'name' => 'Oriya',
    'native' => 'Oriya',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'or',
    'weight' => 0,
  );
  // Exported language: os.
  $languages['os'] = array(
    'language' => 'os',
    'name' => 'Ossetian',
    'native' => 'Ossetian',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'os',
    'weight' => 0,
  );
  // Exported language: pa.
  $languages['pa'] = array(
    'language' => 'pa',
    'name' => 'Punjabi',
    'native' => 'Punjabi',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'pa',
    'weight' => 0,
  );
  // Exported language: pi.
  $languages['pi'] = array(
    'language' => 'pi',
    'name' => 'Pali',
    'native' => 'Pali',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'pi',
    'weight' => 0,
  );
  // Exported language: pl.
  $languages['pl'] = array(
    'language' => 'pl',
    'name' => 'Polish',
    'native' => 'Polski',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'pl',
    'weight' => 0,
  );
  // Exported language: ps.
  $languages['ps'] = array(
    'language' => 'ps',
    'name' => 'Pashto',
    'native' => 'پښتو',
    'direction' => 1,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ps',
    'weight' => 0,
  );
  // Exported language: pt.
  $languages['pt'] = array(
    'language' => 'pt',
    'name' => 'Portuguese, International',
    'native' => 'Portuguese, International',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'pt',
    'weight' => 0,
  );
  // Exported language: qu.
  $languages['qu'] = array(
    'language' => 'qu',
    'name' => 'Quechua',
    'native' => 'Quechua',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'qu',
    'weight' => 0,
  );
  // Exported language: rm.
  $languages['rm'] = array(
    'language' => 'rm',
    'name' => 'Rhaeto-Romance',
    'native' => 'Rhaeto-Romance',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'rm',
    'weight' => 0,
  );
  // Exported language: rn.
  $languages['rn'] = array(
    'language' => 'rn',
    'name' => 'Kirundi',
    'native' => 'Kirundi',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'rn',
    'weight' => 0,
  );
  // Exported language: ro.
  $languages['ro'] = array(
    'language' => 'ro',
    'name' => 'Romanian',
    'native' => 'Română',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ro',
    'weight' => 0,
  );
  // Exported language: ru.
  $languages['ru'] = array(
    'language' => 'ru',
    'name' => 'Russian',
    'native' => 'Русский',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ru',
    'weight' => 0,
  );
  // Exported language: rw.
  $languages['rw'] = array(
    'language' => 'rw',
    'name' => 'Kinyarwanda',
    'native' => 'Kinyarwanda',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'rw',
    'weight' => 0,
  );
  // Exported language: sa.
  $languages['sa'] = array(
    'language' => 'sa',
    'name' => 'Sanskrit',
    'native' => 'Sanskrit',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sa',
    'weight' => 0,
  );
  // Exported language: sc.
  $languages['sc'] = array(
    'language' => 'sc',
    'name' => 'Sardinian',
    'native' => 'Sardinian',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sc',
    'weight' => 0,
  );
  // Exported language: sd.
  $languages['sd'] = array(
    'language' => 'sd',
    'name' => 'Sindhi',
    'native' => 'Sindhi',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sd',
    'weight' => 0,
  );
  // Exported language: se.
  $languages['se'] = array(
    'language' => 'se',
    'name' => 'Northern Sami',
    'native' => 'Northern Sami',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'se',
    'weight' => 0,
  );
  // Exported language: sg.
  $languages['sg'] = array(
    'language' => 'sg',
    'name' => 'Sango',
    'native' => 'Sango',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sg',
    'weight' => 0,
  );
  // Exported language: sh.
  $languages['sh'] = array(
    'language' => 'sh',
    'name' => 'Serbo-Croatian',
    'native' => 'Serbo-Croatian',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sh',
    'weight' => 0,
  );
  // Exported language: si.
  $languages['si'] = array(
    'language' => 'si',
    'name' => 'Sinhala',
    'native' => 'සිංහල',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'si',
    'weight' => 0,
  );
  // Exported language: sk.
  $languages['sk'] = array(
    'language' => 'sk',
    'name' => 'Slovak',
    'native' => 'Slovenčina',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sk',
    'weight' => 0,
  );
  // Exported language: sl.
  $languages['sl'] = array(
    'language' => 'sl',
    'name' => 'Slovenian',
    'native' => 'Slovenščina',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sl',
    'weight' => 0,
  );
  // Exported language: sm.
  $languages['sm'] = array(
    'language' => 'sm',
    'name' => 'Samoan',
    'native' => 'Samoan',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sm',
    'weight' => 0,
  );
  // Exported language: sn.
  $languages['sn'] = array(
    'language' => 'sn',
    'name' => 'Shona',
    'native' => 'Shona',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sn',
    'weight' => 0,
  );
  // Exported language: so.
  $languages['so'] = array(
    'language' => 'so',
    'name' => 'Somali',
    'native' => 'Somali',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'so',
    'weight' => 0,
  );
  // Exported language: sq.
  $languages['sq'] = array(
    'language' => 'sq',
    'name' => 'Albanian',
    'native' => 'Shqip',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sq',
    'weight' => 0,
  );
  // Exported language: sr.
  $languages['sr'] = array(
    'language' => 'sr',
    'name' => 'Serbian',
    'native' => 'Српски',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sr',
    'weight' => 0,
  );
  // Exported language: ss.
  $languages['ss'] = array(
    'language' => 'ss',
    'name' => 'Siswati',
    'native' => 'Siswati',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ss',
    'weight' => 0,
  );
  // Exported language: st.
  $languages['st'] = array(
    'language' => 'st',
    'name' => 'Sesotho',
    'native' => 'Sesotho',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'st',
    'weight' => 0,
  );
  // Exported language: su.
  $languages['su'] = array(
    'language' => 'su',
    'name' => 'Sudanese',
    'native' => 'Sudanese',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'su',
    'weight' => 0,
  );
  // Exported language: sv.
  $languages['sv'] = array(
    'language' => 'sv',
    'name' => 'Swedish',
    'native' => 'Svenska',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sv',
    'weight' => 0,
  );
  // Exported language: sw.
  $languages['sw'] = array(
    'language' => 'sw',
    'name' => 'Swahili',
    'native' => 'Kiswahili',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'sw',
    'weight' => 0,
  );
  // Exported language: ta.
  $languages['ta'] = array(
    'language' => 'ta',
    'name' => 'Tamil',
    'native' => 'தமிழ்',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ta',
    'weight' => 0,
  );
  // Exported language: te.
  $languages['te'] = array(
    'language' => 'te',
    'name' => 'Telugu',
    'native' => 'తెలుగు',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'te',
    'weight' => 0,
  );
  // Exported language: tg.
  $languages['tg'] = array(
    'language' => 'tg',
    'name' => 'Tajik',
    'native' => 'Tajik',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'tg',
    'weight' => 0,
  );
  // Exported language: th.
  $languages['th'] = array(
    'language' => 'th',
    'name' => 'Thai',
    'native' => 'ภาษาไทย',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'th',
    'weight' => 0,
  );
  // Exported language: ti.
  $languages['ti'] = array(
    'language' => 'ti',
    'name' => 'Tigrinya',
    'native' => 'Tigrinya',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ti',
    'weight' => 0,
  );
  // Exported language: tk.
  $languages['tk'] = array(
    'language' => 'tk',
    'name' => 'Turkmen',
    'native' => 'Turkmen',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'tk',
    'weight' => 0,
  );
  // Exported language: tl.
  $languages['tl'] = array(
    'language' => 'tl',
    'name' => 'Tagalog',
    'native' => 'Tagalog',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'tl',
    'weight' => 0,
  );
  // Exported language: tn.
  $languages['tn'] = array(
    'language' => 'tn',
    'name' => 'Setswana',
    'native' => 'Setswana',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'tn',
    'weight' => 0,
  );
  // Exported language: to.
  $languages['to'] = array(
    'language' => 'to',
    'name' => 'Tonga',
    'native' => 'Tonga',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'to',
    'weight' => 0,
  );
  // Exported language: tr.
  $languages['tr'] = array(
    'language' => 'tr',
    'name' => 'Turkish',
    'native' => 'Türkçe',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'tr',
    'weight' => 0,
  );
  // Exported language: ts.
  $languages['ts'] = array(
    'language' => 'ts',
    'name' => 'Tsonga',
    'native' => 'Tsonga',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ts',
    'weight' => 0,
  );
  // Exported language: tt.
  $languages['tt'] = array(
    'language' => 'tt',
    'name' => 'Tatar',
    'native' => 'Tatarça',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'tt',
    'weight' => 0,
  );
  // Exported language: tw.
  $languages['tw'] = array(
    'language' => 'tw',
    'name' => 'Twi',
    'native' => 'Twi',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'tw',
    'weight' => 0,
  );
  // Exported language: ty.
  $languages['ty'] = array(
    'language' => 'ty',
    'name' => 'Tahitian',
    'native' => 'Tahitian',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ty',
    'weight' => 0,
  );
  // Exported language: ug.
  $languages['ug'] = array(
    'language' => 'ug',
    'name' => 'Uyghur',
    'native' => 'Uyghur',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ug',
    'weight' => 0,
  );
  // Exported language: uk.
  $languages['uk'] = array(
    'language' => 'uk',
    'name' => 'Ukrainian',
    'native' => 'Українська',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'uk',
    'weight' => 0,
  );
  // Exported language: ur.
  $languages['ur'] = array(
    'language' => 'ur',
    'name' => 'Urdu',
    'native' => 'اردو',
    'direction' => 1,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'ur',
    'weight' => 0,
  );
  // Exported language: uz.
  $languages['uz'] = array(
    'language' => 'uz',
    'name' => 'Uzbek',
    'native' => 'o\'zbek',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'uz',
    'weight' => 0,
  );
  // Exported language: ve.
  $languages['ve'] = array(
    'language' => 've',
    'name' => 'Venda',
    'native' => 'Venda',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 've',
    'weight' => 0,
  );
  // Exported language: vi.
  $languages['vi'] = array(
    'language' => 'vi',
    'name' => 'Vietnamese',
    'native' => 'Tiếng Việt',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'vi',
    'weight' => 0,
  );
  // Exported language: wo.
  $languages['wo'] = array(
    'language' => 'wo',
    'name' => 'Wolof',
    'native' => 'Wolof',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'wo',
    'weight' => 0,
  );
  // Exported language: xh.
  $languages['xh'] = array(
    'language' => 'xh',
    'name' => 'Xhosa',
    'native' => 'isiXhosa',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'xh',
    'weight' => 0,
  );
  // Exported language: yi.
  $languages['yi'] = array(
    'language' => 'yi',
    'name' => 'Yiddish',
    'native' => 'Yiddish',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'yi',
    'weight' => 0,
  );
  // Exported language: yo.
  $languages['yo'] = array(
    'language' => 'yo',
    'name' => 'Yoruba',
    'native' => 'Yorùbá',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'yo',
    'weight' => 0,
  );
  // Exported language: za.
  $languages['za'] = array(
    'language' => 'za',
    'name' => 'Zhuang',
    'native' => 'Zhuang',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'za',
    'weight' => 0,
  );
  // Exported language: zu.
  $languages['zu'] = array(
    'language' => 'zu',
    'name' => 'Zulu',
    'native' => 'isiZulu',
    'direction' => 0,
    'enabled' => 1,
    'plurals' => 0,
    'formula' => '',
    'domain' => '',
    'prefix' => 'zu',
    'weight' => 0,
  );
  return $languages;
}
