<?PHP

function serchilo_legacy_menu() {

  $items = array();

  $items['commands'] = array(
    'page callback' => 'serchilo_legacy_redirect_commands',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'serchilo_legacy.redirect.inc',
  );

  // Redirect old command URLs

  $items['command/%'] = array(
    'page callback' => 'serchilo_legacy_redirect_command',
    'page arguments' => array(1,2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'serchilo_legacy.redirect.inc',
  );

  return $items;
}
